In [47]:
import numpy as np

streetlights = np.array( [ [1, 0, 1],
                           [0, 1, 1],
                           [0, 0, 1],
                           [1, 1, 1],
                           [0, 1, 1],
                           [1, 0, 1]])

walk_vs_stop = np.array( [ [0],
                           [1],
                           [0],
                           [1],
                           [1],
                           [0] ] )

In [48]:
import numpy as np
weights = np.array([0.5, 0.48, -0.7])
alpha = 0.1

streetlights = np.array( [ [1, 0, 1],
                           [0, 1, 1],
                           [0, 0, 1],
                           [1, 1, 1],
                           [0, 1, 1],
                           [1, 0, 1]])

walk_vs_stop = np.array( [ 0, 1, 0, 1, 1, 0] )

input = streetlights[0]
goal_prediction = walk_vs_stop[0]

for iteration in range(20):
    prediction = input.dot(weights)
    error = (goal_prediction - prediction) ** 2
    delta = prediction - goal_prediction
    weights = weights - (alpha * (input * delta))

    print("Error:" + str(error) + ", Prediction:" + str(prediction))


Error:0.03999999999999998, Prediction:-0.19999999999999996
Error:0.025599999999999973, Prediction:-0.15999999999999992
Error:0.01638399999999997, Prediction:-0.1279999999999999
Error:0.010485759999999964, Prediction:-0.10239999999999982
Error:0.006710886399999962, Prediction:-0.08191999999999977
Error:0.004294967295999976, Prediction:-0.06553599999999982
Error:0.002748779069439994, Prediction:-0.05242879999999994
Error:0.0017592186044416036, Prediction:-0.04194304000000004
Error:0.0011258999068426293, Prediction:-0.03355443200000008
Error:0.0007205759403792803, Prediction:-0.02684354560000002
Error:0.0004611686018427356, Prediction:-0.021474836479999926
Error:0.0002951479051793508, Prediction:-0.01717986918399994
Error:0.00018889465931478573, Prediction:-0.013743895347199997
Error:0.00012089258196146188, Prediction:-0.010995116277759953
Error:7.737125245533561e-05, Prediction:-0.008796093022207963
Error:4.951760157141604e-05, Prediction:-0.007036874417766459
Error:3.169126500570676e-05

In [53]:
import numpy as np

a = np.array([0, 1, 2, 1])
b = np.array([2, 2, 2, 3])
c = 0.5

print( a * b )
print( a + b )
print( a * c )
print( a + c )
print( a ** 2)

d = np.array([1,2,1])
e = np.array([3,6,4])
print( d.dot(e))

[0 2 4 3]
[2 3 4 4]
[0.  0.5 1.  0.5]
[0.5 1.5 2.5 1.5]
[0 1 4 1]
19


In [71]:
#error 공유
import numpy as np
weights = np.array([0.5, 0.48, 0.7])
alpha = 0.1

streetlights = np.array( [ [1, 0, 1],
                           [0, 1, 1],
                           [0, 0, 1],
                           [1, 1, 1],
                           [0, 1, 1],
                           [1, 0, 1]])

walk_vs_stop = np.array( [ 0, 1, 0, 1, 1, 0] )

input = streetlights[0]
goal_prediction = walk_vs_stop[0]

for iteration in range(40):
    error_for_all_lights = 0
    for row_index in range(len(walk_vs_stop)):
        input = streetlights[row_index]
        goal_prediction = walk_vs_stop[row_index]

        prediction = input.dot(weights)

        error = (goal_prediction - prediction) ** 2
        error_for_all_lights += error

        delta = prediction - goal_prediction
        weights = weights - (alpha * (input * delta))
        print("Prediction:" + str(prediction))
        print("Weights: " + str(weights))

    print("Error:" + str(error_for_all_lights) + "\n")
print("Weights: " + str(weights))

Prediction:1.2
Weights: [0.38 0.48 0.58]
Prediction:1.06
Weights: [0.38  0.474 0.574]
Prediction:0.574
Weights: [0.38   0.474  0.5166]
Prediction:1.3706
Weights: [0.34294 0.43694 0.47954]
Prediction:0.91648
Weights: [0.34294  0.445292 0.487892]
Prediction:0.830832
Weights: [0.2598568 0.445292  0.4048088]
Error:2.6076777626239998

Prediction:0.6646656
Weights: [0.19339024 0.445292   0.33834224]
Prediction:0.78363424
Weights: [0.19339024 0.46692858 0.35997882]
Prediction:0.359978816
Weights: [0.19339024 0.46692858 0.32398093]
Prediction:0.9842997504
Weights: [0.19496026 0.4684986  0.32555096]
Prediction:0.7940495603200001
Weights: [0.19496026 0.48909364 0.346146  ]
Prediction:0.541106268288
Weights: [0.14084964 0.48909364 0.29203538]
Error:0.953637324914952

Prediction:0.43288501463039997
Weights: [0.09756114 0.48909364 0.24874688]
Prediction:0.73784051996416
Weights: [0.09756114 0.51530959 0.27496282]
Prediction:0.27496282303974395
Weights: [0.09756114 0.51530959 0.24746654]
Prediction:

In [72]:
#error 나누기
import numpy as np
weights = np.array([0.5, 0.48, -0.7])
alpha = 0.01

streetlights = np.array( [ [1, 0, 1],
                           [0, 1, 1],
                           [0, 0, 1],
                           [1, 1, 1],
                           [0, 1, 1],
                           [1, 0, 1]])

walk_vs_stop = np.array( [ 0, 1, 0, 1, 1, 0] )

input = streetlights[0]
goal_prediction = walk_vs_stop[0]
error_for_all_lights = 0
for iteration in range(10000):
    error_for_all_lights = 0
    for row_index in range(len(walk_vs_stop)):
        input = streetlights[row_index]
        goal_prediction = walk_vs_stop[row_index]


        prediction0 = input[0] * weights[0]
        prediction1 = input[1] * weights[1]
        prediction2 = input[2] * weights[2]

        error0 = (goal_prediction - prediction0) ** 2
        error1 = (goal_prediction - prediction1) ** 2
        error2 = (goal_prediction - prediction2) ** 2

        delta0 = prediction0 - goal_prediction
        delta1 = prediction1 - goal_prediction
        delta2 = prediction2 - goal_prediction

        weights[0] = weights[0] - (alpha * (input[0] * delta0))
        weights[1] = weights[1] - (alpha * (input[1] * delta1))
        weights[2] = weights[2] - (alpha * (input[2] * delta2))

        prediction = input.dot(weights)
        error = (goal_prediction - prediction) ** 2
        error_for_all_lights += error

        #weights = weights - (alpha * (input * delta))
        #print("Prediction:" + str(prediction))

    #print("Error:" + str(error_for_all_lights) + "\n")
print("Error:" + str(error_for_all_lights) + "\n")
print("Weights: " + str(weights))

Error:2.8317749534529755

Weights: [0.33332211 1.         0.50080374]


In [2]:
import numpy as np

np.random.seed(1)

def relu(x):
    return (x > 0) * x

alpha = 0.2
hidden_size = 4

streetlights = np.array( [ [1,0,1],
                           [0,1,1],
                           [0,0,1],
                           [1,1,1]])

walk_vs_stop = np.array([[1,1,0,0]]).T

weights_0_1 = 2*np.random.random((3, hidden_size)) - 1
weights_1_2 = 2*np.random.random((hidden_size, 1)) - 1

# print(weights_0_1)
# print(weights_1_2)

layer_0 = streetlights[0]
layer_1 = relu(np.dot(layer_0,weights_0_1))
layer_2 = np.dot(layer_1, weights_1_2)

In [12]:

import numpy as np

np.random.seed(1)

streetlights = np.array( [ [1,0,1],
                           [0,1,1],
                           [0,0,1],
                           [1,1,1]])

walk_vs_stop = np.array([[1,1,0,0]]).T

def relu(x):
    return (x > 0) * x

def relu2deriv(output):
    return output > 0

alpha = 0.2
hidden_size = 4

weights_0_1 = 2*np.random.random((3, hidden_size)) - 1
weights_1_2 = 2*np.random.random((hidden_size, 1)) - 1

for iteration in range(60):
    layer_2_error = 0
    for i in range(len(streetlights)):
        layer_0 = streetlights[i:i+1]
        layer_1 = relu(np.dot(layer_0, weights_0_1))
        layer_2 = np.dot(layer_1, weights_1_2)

        layer_2_error += np.sum((layer_2 - walk_vs_stop[i:i+1]) ** 2)
        layer_2_delta = (walk_vs_stop[i:i+1] - layer_2)
        layer_1_delta = layer_2_delta.dot(weights_1_2.T)*relu2deriv(layer_1)

        weights_1_2 += alpha * layer_1.T.dot(layer_2_delta)
        weights_0_1 += alpha * layer_0.T.dot(layer_1_delta)

    if (iteration % 10 == 9):
        print("Error: " + str(layer_2_error))

Error: 0.6342311598444467
Error: 0.35838407676317513
Error: 0.0830183113303298
Error: 0.006467054957103705
Error: 0.0003292669000750734
Error: 1.5055622665134859e-05


In [17]:
import numpy as np

np.random.seed(1)

def relu(x):
    return (x > 0) * x

def relu2deriv(output):
    return output > 0

lights = np.array( [[1,0,1],
                    [0,1,1],
                    [0,0,1],
                    [1,1,1]])

walk_stop = np.array([[1,1,0,0]]).T

alpha = 0.2
hidden_size = 3

weights_0_1 = 2*np.random.random((3, hidden_size)) - 1
weights_1_2 = 2*np.random.random((hidden_size, 1)) - 1

layer_0 = lights[0:1]
layer_1 = np.dot(layer_0, weights_0_1)
layer_1 = relu(layer_1)
layer_2 = np.dot(layer_1, weights_1_2)

error = (layer_2 - walk_vs_stop[0:1]) ** 2

layer_2_delta = (layer_2 - walk_vs_stop[0:1])

layer_1_delta = layer_2_delta.dot(weights_1_2.T)
layer_1_delta *= relu2deriv(layer_1)

weight_delta_1_2 = layer_1.T.dot(layer_2_delta)
weight_delta_0_1 = layer_0.T.dot(layer_1_delta)

weights_1_2 -= alpha * weight_delta_1_2
weights_0_1 -= alpha * weight_delta_0_1

print(weights_1_2)
print(weights_0_1)

[[ 0.07763347]
 [-0.13469566]
 [ 0.370439  ]]
[[-0.16595599  0.40763847 -0.99977125]
 [-0.39533485 -0.70648822 -0.81532281]
 [-0.62747958 -0.34188906 -0.20646505]]


In [60]:
import numpy as np

np.random.seed(1)

def relu(x):
    return (x > 0) * x

def relu2deriv(output):
    return output > 0

lights = np.array( [[1,0,1],
                    [0,1,1],
                    [0,0,1],
                    [1,1,1]])

walk_vs_stop = np.array([[ 1, 1, 0, 0]]).T

alpha = 0.2
hidden_size = 4

weights_0_1 = 2*np.random.random((3, hidden_size)) - 1
weights_1_2 = 2*np.random.random((hidden_size, 1)) - 1

for iteration in range(60):
    layer_2_error = 0
    for i in range(len(lights)):
        layer_0 = lights[i:i+1]
        layer_1 = relu(np.dot(layer_0, weights_0_1))
        layer_2 = np.dot(layer_1, weights_1_2)

        layer_2_error += np.sum( (layer_2 - walk_vs_stop[i:i+1]) ** 2 )

        layer_2_delta = (layer_2 - walk_vs_stop[i:i+1])
        layer_1_delta = layer_2_delta.dot(weights_1_2.T) * relu2deriv(layer_1)

        weights_1_2 -= alpha * layer_1.T.dot(layer_2_delta)
        weights_0_1 -= alpha * layer_0.T.dot(layer_1_delta)

    if (iteration % 10 == 9):
        print("Error:" + str(layer_2_error))

Error:0.20210946321033732
Error:0.00571939320892546
Error:3.4923867952835144e-05
Error:1.6949506644663992e-07
Error:8.082290034284634e-10
Error:3.849277233772149e-12


In [1]:
import numpy as np

np.random.seed(1)

input = np.array([ [0,0],
                   [1,0],
                   [0,1],
                   [1,1]])
output = np.array([ [0,1,1,0] ]).T

def relu(x):
    return x * (x > 0)

# def relu(x):
#     return 1 / (1 + np.exp(-x))

def relu2deriv(output):
    return output > 0

alpha = 0.1
hidden_size = 6

weights_0_1 = np.random.random((2,hidden_size))
weights_1_2 = np.random.random((hidden_size, 1))
#
# weights_0_1 = np.array([[0.6,0.4],[0.3,0.7]])
# weights_1_2 = np.array([[0.1],[0.8]] )

print(weights_0_1)
print(weights_1_2)

for i in range(100):
    layer_2_error = 0
    prediction = 0
    for j in range(len(input)):
        layer_0 = input[j:j+1]
        layer_1 = relu(np.dot(layer_0, weights_0_1))
        layer_2 = np.dot(layer_1, weights_1_2)
        # print(output[j] , layer_2)

        layer_2_error += np.sum( (layer_2 - output[j:j+1]) ** 2)
        layer_2_delta = (layer_2 - output[j:j+1])
        layer_1_delta = np.dot(layer_2_delta, weights_1_2.T ) * relu2deriv(layer_1)
        # layer_1_delta = layer_2_delta.dot(weights_1_2.T) * relu2deriv(layer_1)

        weights_1_2 -= alpha * layer_1.T.dot(layer_2_delta)
        weights_0_1 -= alpha * layer_0.T.dot(layer_1_delta)


    print("Error:" + str(layer_2_error))

    # if (i % 10 == 9):
    #     print("Error:" + str(layer_2_error))

# for iteration in range(1000):
#     layer_2_error = 0
#     for i in range(len(input)):
#         layer_0 = input[i:i+1]
#         layer_1 = relu(np.dot(layer_0, weights_0_1))
#         layer_2 = np.dot(layer_1, weights_1_2)
#
#         layer_2_error += np.sum( (layer_2 - output[i:i+1]) ** 2 )
#
#         layer_2_delta = (layer_2 - output[i:i+1])
#         layer_1_delta = layer_2_delta.dot(weights_1_2.T) * relu2deriv(layer_1)
#
#         weights_1_2 -= alpha * layer_1.T.dot(layer_2_delta)
#         weights_0_1 -= alpha * layer_0.T.dot(layer_1_delta)
#
#     if (iteration % 100 == 99):
#         print("Error:" + str(layer_2_error))

print(weights_0_1)
print(weights_1_2)

[[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01
  1.46755891e-01 9.23385948e-02]
 [1.86260211e-01 3.45560727e-01 3.96767474e-01 5.38816734e-01
  4.19194514e-01 6.85219500e-01]]
[[0.20445225]
 [0.87811744]
 [0.02738759]
 [0.67046751]
 [0.4173048 ]
 [0.55868983]]
Error:4.905366043715536
Error:1.805231779711352
Error:1.5807644813069834
Error:1.5163601474797677
Error:1.487138070769791
Error:1.4674082606614338
Error:1.4489881760812697
Error:1.4329459700986384
Error:1.4144159767487838
Error:1.394478499024265
Error:1.3721847416336674
Error:1.350035757180975
Error:1.324667178741239
Error:1.2964600653347316
Error:1.2679903832777852
Error:1.2359279487740715
Error:1.200778143942535
Error:1.164960397750782
Error:1.142816529244583
Error:1.1060269474954414
Error:1.0874430811395
Error:1.046051399709966
Error:1.0318408004965038
Error:0.9906432946547602
Error:0.9673819308888549
Error:0.9401241795143727
Error:0.8978125563066964
Error:0.8896464108099003
Error:0.8344613667086556
Error:0.7856